# permissions for end users to view nodejobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodejob-viewer-role
rules:
- apiGroups:
  - tool.tanx.io
  resources:
  - nodejobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tool.tanx.io
  resources:
  - nodejobs/status
  verbs:
  - get
